import { BugFixJob, Config } from "./types.js";
import { getWorkItemDetails, getRepositories, createPullRequest } from "./azure-devops-client.js";
import {
  cloneRepo,
  sanitizeBranchName,
  hasChanges,
  getChangeSummary,
  createBranchAndCommit,
  pushBranch,
  cleanup,
} from "./git-operations.js";
import { buildAgentPrompt } from "./prompt-builder.js";
import { runAgent } from "./agent-runner.js";

export async function processBugFixJob(
  job: BugFixJob,
  config: Config
): Promise<void> {
  let workDir: string | undefined;

  try {
    // 1. Fetch full work item details
    console.log(`[Pipeline] Fetching work item #${job.workItemId}...`);
    const workItem = await getWorkItemDetails(
      job.workItemId,
      job.projectName,
      config
    );

    // 2. Determine repository
    console.log(`[Pipeline] Looking up repositories for project '${job.projectName}'...`);
    const repos = await getRepositories(job.projectName, config);
    if (repos.length === 0) {
      throw new Error(`No repositories found in project '${job.projectName}'`);
    }
    const repo = repos[0];

    // 3. Clone repo to temp dir
    console.log(`[Pipeline] Cloning repository '${repo.name}'...`);
    const cloneResult = await cloneRepo(repo.remoteUrl, config.azureDevOpsPat);
    workDir = cloneResult.workDir;

    // 4. Build prompt
    const prompt = buildAgentPrompt(workItem);

    // 5. Run Claude agent
    console.log(`[Pipeline] Running Claude agent for bug #${job.workItemId}...`);
    const agentResult = await runAgent(prompt, workDir, config);

    if (!agentResult.success) {
      console.log(`[Pipeline] Agent could not fix bug #${job.workItemId}: ${agentResult.analysis}`);
      return;
    }

    // 6. Check if agent made changes
    const changed = await hasChanges(workDir);
    if (!changed) {
      console.log(`[Pipeline] Agent made no file changes for bug #${job.workItemId}.`);
      return;
    }

    // 7. Create branch, commit, push
    const branchName = sanitizeBranchName(job.workItemId, workItem.title);
    const commitMessage = `fix: ${workItem.title} (WI #${job.workItemId})`;
    console.log(`[Pipeline] Creating branch '${branchName}' and pushing...`);
    await createBranchAndCommit(workDir, branchName, commitMessage);
    await pushBranch(workDir, branchName);

    // 8. Create PR
    const changeSummary = await getChangeSummary(workDir);
    const targetBranch = config.targetBranch;
    const prDescription = buildPrDescription(workItem, agentResult, changeSummary);

    console.log(`[Pipeline] Creating pull request...`);
    const pr = await createPullRequest(
      job.projectName,
      repo.id,
      {
        sourceRefName: `refs/heads/${branchName}`,
        targetRefName: `refs/heads/${targetBranch}`,
        title: `Fix: ${workItem.title} (WI #${job.workItemId})`,
        description: prDescription,
        workItemId: job.workItemId,
      },
      config
    );

    console.log(`[Pipeline] PR created successfully: ${pr.url ?? pr.pullRequestId}`);
  } finally {
    // 9. Cleanup
    if (workDir) {
      await cleanup(workDir);
    }
  }
}

function buildPrDescription(
  workItem: { id: number; title: string; severity: string; priority: string },
  agentResult: { analysis: string; costUsd: number },
  changeSummary: string
): string {
  return `## Automated Fix by ReviewSyndrome Agent

**Bug**: #${workItem.id} — ${workItem.title}
**Severity**: ${workItem.severity} | **Priority**: ${workItem.priority}

### Root Cause Analysis
${agentResult.analysis}

### Changes Made
\`\`\`
${changeSummary}
\`\`\`

---

> This PR was automatically generated by **ReviewSyndrome Agent** using Claude Sonnet.
> Please review carefully before merging.
> AI-generated cost: ~$${agentResult.costUsd.toFixed(2)}`;
}
